---
- name: Find the cloud model
  set_fact:
    cloud_model_file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ cloud_model }}.yml"
        - "{{ cloud_model }}.yaml"
        - "{{ cloud_model }}"
      paths:
        - "{{ cloud_model_dir }}"
        - "{{ playbook_dir }}"
        - "{{ inventory_dir }}"

- name: Read in the Cloud Model {{ cloud_model }}
  include_vars:
    file: "{{ cloud_model_file }}"

- include_tasks: "{{ cloud_vpc_data.provider }}-template.yml"
  vars:
      cloud_vpc_name: "{{ cloud_vpc_data.name }}"
      cloud_network_data: "{{ cloud_vpc_data.networks | default([]) }}"
      cloud_security_group_data: "{{ cloud_acls | default([]) }}"
      cloud_instance_data: "{{ cloud_vpc_data.instances | default([]) }}"
  with_items: "{{ vpc_list | default([]) }}"
  loop_control:
    loop_var: cloud_vpc_data
